language: csharp

# Add build number to version
before_script: sed -ri "s/VersionNumber\((.*), 0\)/VersionNumber(\1, $TRAVIS_BUILD_NUMBER)/g" Oxide.Ext.Rust/RustExtension.cs

# Build the project
solution: Rust.sln

# Run deployment script
after_success: "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == OxideMod/Rust ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  # IRC notification
  irc: "chat.freenode.net#oxidemod"

# Environmental system variables
env:
  global:
    # Super secure, encrypted variables! Ssssh!
    - secure: "JL/xkAPKqcYj0aGhg28liVUCDhDmPMbVpoJPgoAiGsNdF9NYIoFhr/nUK7icsyGFZezre47ENRzVIJRVvhJYr6ZvQ14m7UxyqopXLW1hMG1gLw2OiSsHcb0g0Ug/1rMNvxe3CBUw/MOkC7l7kEb0dEtY8HnFTW1uxUzxqa//I4w="
